;;; Use CLPM with default configuration.
;;;
;;; Generated by CLPM 0.4.1

(require "asdf")
#-clpm-client
(when (asdf:find-system "clpm-client" nil)
  ;; Load the CLPM client if we can find it.
  (asdf:load-system "clpm-client")
  (when (uiop:symbol-call :clpm-client '#:active-context)
    ;; If started inside a context (i.e., with `clpm exec` or `clpm bundle exec`),
    ;; activate ASDF integration
    (uiop:symbol-call :clpm-client '#:activate-asdf-integration)))
