#!/bin/sh
set -ex

find . -type f | grep -v Windows | grep -v iac | grep -v \.git | while read file
do
    dest=${HOME}/$(echo $file | sed -e 's|dot-|.|g' -e 's|^\./||')
    destdir=$(echo "${dest}" | sed -e 's|[^/]\{1,\}$||')
    mkdir -p $destdir
    rm -f $dest
    cp $file $dest
done
