#!/bin/sh
set -ex

find . -name 'dot-*' | while read dotfile
do
    dest=$(echo "${dotfile}" | sed 's|^dot-|.|')
    if [ -L "${HOME}/${dest}" ]
    then
        rm "${HOME}/${dest}"
    elif [ -f "${HOME}/${dest}" ]
    then
        echo "Warning: ${HOME}/${dest} already exists and is not a directory or symlink. Skipping."
    elif [ -d "${HOME}/${dest}" ]
    then
        rsync -avHAX "${dotfile}/" "${HOME}/${dest}"
    elif [ -f "${dotfile}" ]
    then
        rsync -avHAX "${dotfile}" "${HOME}/${dest}"
    else
        echo "Warning: ${dotfile} is not a file or directory. Skipping."
    fi
done
