#!/bin/sh

ENTER="28:1 28:0"
ALT_TAB="56:1 15:1 15:0 56:0"
TAB="56:1 56:0"
CTRL_C="29:0 46:1 46:0 29:0"
CTRL_V="29:0 47:1 47:0 29:0"
CTRL_B="29:0 48:1 48:0 29:0"
CTRL_T="29:1 20:1 20:0 29:0"
CTRL_F="29:1 33:1 33:0 29:0"

ydotool key ${ALT_TAB} ${CTRL_F}
ydotool type "$(paste)"
ydotool key ${TAB} ${TAB} ${TAB} ${TAB}
ydotool key ${CTRL_B} ${ALT_TAB} ${CTRL_V} ${ALT_TAB} ${CTRL_C} ${ALT_TAB} ${CTRL_V} ${ENTER}
if [ "${1}" = "TOTP" ]
then
    sleep 1.5
    ydotool key ${ALT_TAB} ${CTRL_T} ${ALT_TAB} ${CTRL_V}
ydotool key ${ALT_TAB}


${CTRL_ 56:1 15:1 15:0 56:0 29:1 48:1 48:0 29:0 56:1 15:1 15:0 56:0 29:1 47:1 47:0 29:0