#!/bin/sh

set -ex

src="${1}"

if [ ! -f "${src}" ]
then
  echo "File not found: ${src}" >&2
  exit 1
fi

dest=$(echo "${1}" | sed -e "s|${HOME}/*||" -e "s/^[.]/dot-/")
destdir=$(echo "${dest}" | sed -e 's|/[^/]*$||')

if echo "${destdir}" | grep -q '/'
then
    mkdir -p "${destdir}"
fi

cp "${src}" "${dest}"