downloads-dir = "C:\\Users\\bhw\\Downloads"
[skin]
backend = "imap"
email = "me@djha.skin"
default = false
display-name = "Skin"
sender = "smtp"
smtp-host = "smtp.migadu.com"
smtp-port = 465
smtp-ssl = true
smtp-login = "me@djha.skin"
smtp-passwd-cmd = 'multipass smtp://smtp.migadu.com:445/ me@djha.skin'
sync = true
imap-host = "imap.migadu.com"
imap-port = 993
imap-ssl = true
imap-login = "me@djha.skin"
imap-passwd-cmd = 'multipass imap://imap.migadu.com:993/ me@djha.skin'

[skin.folder-aliases]
archive = "Archives/2023"
inbox = "INBOX"
sent = "Sent"
trash = "Trash"
drafts = "Drafts"
junk = "Junk"

[gmail]
backend = "imap"
email = "djhaskin987@gmail.com"
default = false
display-name = "Daniel Jay Haskin"
sender = "smtp"
smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-ssl = true
smtp-login = "djhaskin987@gmail.com"
smtp-passwd-cmd = 'multipass smtp://smtp.gmail.com:445/ djhaskin987@gmail.com'
sync = true
imap-host = "imap.gmail.com"
imap-port = 993
imap-ssl = true
imap-login = "djhaskin987@gmail.com"
imap-passwd-cmd = 'multipass imap://imap.gmail.com:993/ djhaskin987@gmail.com'

[gmail.folder-aliases]
archive = "[Gmail]/All Mail"
inbox = "INBOX"
sent = "[Gmail]/Sent Mail"
drafts = "[Gmail]/Drafts"
trash = "[Gmail]/Trash"
junk = "[Gmail]/Spam"
